name: Reusable Python CI Pipeline

on:
  workflow_call:
    inputs:
      python_version:
        type: string
        default: "3.11"
      target_paths:
        type: string
        required: true
        description: "Space or newline separated paths to scan"
      run_pylint:
        type: boolean
        default: true
      run_security:
        type: boolean
        default: true

permissions:
  contents: read

jobs:
  pylint:
    name: Pylint Check
    if: inputs.run_pylint
    runs-on: ubuntu-latest

    container:
      image: hrituja/python-pytest:v1

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ inputs.python_version }}

      - name: Run pylint
        shell: bash
        run: |
          echo "Running pylint on:"
          echo "${{ inputs.target_paths }}"

          export PYTHONPATH="$PWD"

          # Convert multiline input into space-separated args
          TARGETS=$(echo "${{ inputs.target_paths }}" | xargs)

          pylint $TARGETS --fail-under=8



  security:
    name: Security Scan (Bandit)
    if: inputs.run_security
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ inputs.python_version }}

      - name: Install bandit
        run: |
          python -m pip install --upgrade pip
          pip install bandit

      - name: Run Bandit
        shell: bash
        run: |
          echo "Running Bandit on:"
          echo "${{ inputs.target_paths }}" | while IFS= read -r path; do
            [ -z "$path" ] && continue
            echo " - $path"
            bandit -r "$path" -s B101
          done

